"""

Revision ID: 1d3b62e9ab5a
Revises: ef6843a7f95e
Create Date: 2019-02-20 22:42:05.942063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3b62e9ab5a'
down_revision = 'ef6843a7f95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
