"""

Revision ID: 7e08d0fcaac8
Revises: ff82ecfdca82
Create Date: 2019-02-20 22:35:03.267283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e08d0fcaac8'
down_revision = 'ff82ecfdca82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
