"""trial for new package

Revision ID: 7f53156a0ac4
Revises: 1d3b62e9ab5a
Create Date: 2019-02-26 22:23:28.485787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f53156a0ac4'
down_revision = '1d3b62e9ab5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'product_id')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('salt', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'token')
    op.drop_column('users', 'salt')
    op.drop_column('users', 'password')
    op.add_column('order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_product_id_fkey', 'order', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
