"""users Table added

Revision ID: d53a8a114002
Revises: 6dfc21e5a2b0
Create Date: 2019-02-17 16:34:28.869860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd53a8a114002'
down_revision = '6dfc21e5a2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('contact_info', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('users', 'contact_info')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
