"""

Revision ID: ef6843a7f95e
Revises: 7e08d0fcaac8
Create Date: 2019-02-20 22:35:41.183807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6843a7f95e'
down_revision = '7e08d0fcaac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
