"""order table relation added

Revision ID: fdbd1aa5a068
Revises: c37ad8976968
Create Date: 2019-02-20 21:36:44.761044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbd1aa5a068'
down_revision = 'c37ad8976968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    op.drop_column('order', 'product_id')
    # ### end Alembic commands ###
