"""

Revision ID: ff82ecfdca82
Revises: fdbd1aa5a068
Create Date: 2019-02-20 21:46:20.790313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff82ecfdca82'
down_revision = 'fdbd1aa5a068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
